apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx4
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  sources:
  - path: nginx
    repoURL: https://github.com/sunnybhambhani/helm
    targetRevision: HEAD
    helm:
      valueFiles:
      - $values/app-of-apps/nginx4-values-dev.yaml
  - repoURL: 'https://github.com/sunnybhambhani/helm'
    targetRevision: HEAD
    ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true