apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx3
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: nginx
    repoURL: https://github.com/sunnybhambhani/helm
    targetRevision: HEAD
    helm:
      parameters:
        - name: service.nodePort
          value: '30003'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true